apiVersion: apps/v1
kind: Deployment
metadata:
  name: alarm-dev
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: alarm
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: alarm
    spec:
      containers:
        - name: alarm
          image: ${DOCKER_IMAGE_TAG}
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
            - name: SPRING_CONFIG_LOCATION
              value: '/etc/secrets/application.yaml'
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
          volumeMounts:
            - name: alarm-secret-application
              mountPath: '/etc/secrets'
              readOnly: true
            - name: alarm-secret-firebase
              mountPath: '/etc/secrets'
              subPath: 'creaite-app-firebase-adminsdk.json'
              readOnly: true
            - name: firebase-service-key
              mountPath: '/etc/secrets'
              subPath: 'firebase_service_key.json'
              readOnly: true
      imagePullSecrets:
        - name: dockerhub-secret
      volumes:
        - name: alarm-secret-application
          secret:
            secretName: alarm-secret
            items:
              - key: application.yaml
                path: application.yaml
        - name: alarm-secret-firebase
          secret:
            secretName: alarm-secret
            items:
              - key: creaite-app-firebase-adminsdk.json
                path: creaite-app-firebase-adminsdk.json
        - name: firebase-service-key
          secret:
            secretName: alarm-secret
            items:
              - key: firebase_service_key.json
                path: firebase_service_key.json
