version: "3.3"
services:
        portainer:
                image: portainer/portainer-ce:latest
                container_name: portainer
                restart: always
                volumes:
                        - ./data:/data
                        - /var/run/docker.sock:/var/run/docker.sock
                ports:
                        - 9443:9443
