apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
  labels:
    name: jenkins
    customLabel: jenkins-pv
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: aws-ebs-sc
  hostPath:
    path: '/data/jenkins'
