apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-proxy-manager-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/mnt/data/nginx-proxy-manager"
