apiVersion: apps/v1
kind: Deployment
metadata:
  name: picture-dev
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: picture
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: picture
    spec:
      containers:
        - name: picture
          image: ${DOCKER_IMAGE_TAG}
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
          volumeMounts:
            - name: picture-secret-application
              mountPath: '/etc/secrets'
              readOnly: true
            - name: picture-secret-firebase
              mountPath: '/creaite-app-firebase-adminsdk.json'
              subPath: 'creaite-app-firebase-adminsdk.json'
              readOnly: true
      imagePullSecrets:
        - name: dockerhub-secret
      volumes:
        - name: picture-secret-application
          secret:
            secretName: picture-secret
            items:
              - key: application.yaml
                path: application.yaml
        - name: picture-secret-firebase
          secret:
            secretName: picture-secret
            items:
              - key: creaite-app-firebase-adminsdk.json
                path: creaite-app-firebase-adminsdk.json
