apiVersion: v1
kind: PersistentVolume
metadata:
  name: elastic-kibana-pv
  labels:
    name:
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName:
  hostPath:
    path: "/data/elastic-kibana"
---
