volumePermissions:
  enabled: true
master:
  replicaCount: 1
data:
  replicaCount: 1
coordinating:
  replicaCount: 1
ingest:
  replicaCount: 1
global:
  kibanaEnabled: true
kibana:
  service:
    type: LoadBalancer
  volumePermissions:
    enabled: true
