apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jenkins-dev
  namespace: dev
spec:
  serviceName: 'jenkins-dev'
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      securityContext:
        runAsUser: 0
      containers:
        - name: jenkins
          image: jenkins/jenkins:lts
          env:
            - name: JAVA_OPTS
              value: -Djenkins.install.runSetupWizard=true
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 50000
              name: agent
          volumeMounts:
            - mountPath: /var/jenkins_home
              name: jenkins-persistent-storage
          command: ['/bin/bash', '-c']
          args:
            - |
              /usr/local/bin/jenkins-plugin-cli --verbose --plugins \
                  github:1.33.1 \
                  workflow-aggregator:2.6 \
                  kubernetes-cd:2.0.0 \
                  docker-workflow:1.26 \
                  git:4.8.2
      volumes:
        - name: jenkins-persistent-storage
          persistentVolumeClaim:
            claimName: jenkins-pv-claim
