apiVersion: v1
kind: Service
metadata:
  name: picture-dev
  namespace: dev
spec:
  selector:
    app: picture
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
