apiVersion: v1
kind: Service
metadata:
  name: mysql-svc-dev
  namespace: dev
  labels:
    app: mysql
spec:
  ports:
    - name: mysql
      port: 3307
  selector:
    app: mysql
  type: LoadBalancer
